;track ids.
.ENUM
	track_wily_defeated
	track_stage_select
	track_boss_show
	track_game_over
	track_boss_defeated
	track_cutman
	track_fireman
	track_fireman
	track_bombman
	track_elecman
	track_gutsman
	track_wily_boss_fighting
	track_wily1_2
	track_boss_fighting
	track_ending
	track_iceman
	track_wily3_4
	track_wily_ufo
	track_explosion
	track_magnet_beam
	track_mega_buster
	track_enemy_bullet
	track_megaman_hit
	track_throw_boulder
	track_refill
	track_landing
	track_pickup_ball
	track_enemy_hit
	track_press_start
	track_enemy_immune
	track_thunder_beam
	track_select
	track_teleport
	track_points
	track_pause
	track_track_platform
	track_door
	track_rolling_cutter
	track_cutman_move
	track_27
	track_earthquake
	track_big_eye
	track_ice_slasher
	track_jump_into_water
	track_appearing_block
	track_fireman_move
	track_fire_storm
	track_2f
	track_flood
	track_megaman_death
	track_1up
.ENDENUM
