;cutman screen id set
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $02
	.BYTE $1C
	.BYTE $1F
	.BYTE $1D
	.BYTE $1E
	.BYTE $01
	.BYTE $02
	.BYTE $03
	.BYTE $06
	.BYTE $04
	.BYTE $05
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F

;wily1 screen id set
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $19
	.BYTE $1A
	.BYTE $15
	.BYTE $1B
	.BYTE $1B

;end
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF

;screen id pointers
	.WORD cutman_wily1_mapset_00
	.WORD cutman_wily1_mapset_01
	.WORD cutman_wily1_mapset_02
	.WORD cutman_wily1_mapset_03
	.WORD cutman_wily1_mapset_04
	.WORD cutman_wily1_mapset_05
	.WORD cutman_wily1_mapset_06
	.WORD cutman_wily1_mapset_07
	.WORD cutman_wily1_mapset_08
	.WORD cutman_wily1_mapset_09
	.WORD cutman_wily1_mapset_0a
	.WORD cutman_wily1_mapset_0b
	.WORD cutman_wily1_mapset_0c
	.WORD cutman_wily1_mapset_0d
	.WORD cutman_wily1_mapset_0e
	.WORD cutman_wily1_mapset_0f
	.WORD cutman_wily1_mapset_10
	.WORD cutman_wily1_mapset_11
	.WORD cutman_wily1_mapset_12
	.WORD cutman_wily1_mapset_13
	.WORD cutman_wily1_mapset_14
	.WORD cutman_wily1_mapset_15
	.WORD cutman_wily1_mapset_16
	.WORD cutman_wily1_mapset_17
	.WORD cutman_wily1_mapset_18
	.WORD cutman_wily1_mapset_19
	.WORD cutman_wily1_mapset_1a
	.WORD cutman_wily1_mapset_1b
	.WORD cutman_wily1_mapset_1c
	.WORD cutman_wily1_mapset_1d
	.WORD cutman_wily1_mapset_1e
	.WORD cutman_wily1_mapset_1f
