;cutman screen id set
	.BYTE $00
	.BYTE $00
	.BYTE $01
	.BYTE $02
	.BYTE $1C
	.BYTE $1F
	.BYTE $1D
	.BYTE $1E
	.BYTE $01
	.BYTE $02
	.BYTE $03
	.BYTE $06
	.BYTE $04
	.BYTE $05
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $0D
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F

;wily1 screen id set
	.BYTE $10
	.BYTE $10
	.BYTE $10
	.BYTE $11
	.BYTE $11
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18
	.BYTE $19
	.BYTE $1A
	.BYTE $15
	.BYTE $1B
	.BYTE $1B

;end
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF

;screen id pointers
	.WORD mapset_cutman_wily1_00
	.WORD mapset_cutman_wily1_01
	.WORD mapset_cutman_wily1_02
	.WORD mapset_cutman_wily1_03
	.WORD mapset_cutman_wily1_04
	.WORD mapset_cutman_wily1_05
	.WORD mapset_cutman_wily1_06
	.WORD mapset_cutman_wily1_07
	.WORD mapset_cutman_wily1_08
	.WORD mapset_cutman_wily1_09
	.WORD mapset_cutman_wily1_0a
	.WORD mapset_cutman_wily1_0b
	.WORD mapset_cutman_wily1_0c
	.WORD mapset_cutman_wily1_0d
	.WORD mapset_cutman_wily1_0e
	.WORD mapset_cutman_wily1_0f
	.WORD mapset_cutman_wily1_10
	.WORD mapset_cutman_wily1_11
	.WORD mapset_cutman_wily1_12
	.WORD mapset_cutman_wily1_13
	.WORD mapset_cutman_wily1_14
	.WORD mapset_cutman_wily1_15
	.WORD mapset_cutman_wily1_16
	.WORD mapset_cutman_wily1_17
	.WORD mapset_cutman_wily1_18
	.WORD mapset_cutman_wily1_19
	.WORD mapset_cutman_wily1_1a
	.WORD mapset_cutman_wily1_1b
	.WORD mapset_cutman_wily1_1c
	.WORD mapset_cutman_wily1_1d
	.WORD mapset_cutman_wily1_1e
	.WORD mapset_cutman_wily1_1f
