objects_set_cutman:
	;      id,   x,   y, object
	.BYTE $01, $10, $4C, objects_bunby_heli
	.BYTE $01, $40, $8C, objects_bunby_heli
	.BYTE $01, $50, $5C, objects_bunby_heli
	.BYTE $02, $38, $4C, objects_bunby_heli
	.BYTE $02, $70, $8C, objects_bunby_heli
	.BYTE $02, $80, $5C, objects_bunby_heli
	.BYTE $03, $38, $48, objects_blaster_left_delayed
	.BYTE $03, $B8, $78, objects_blaster_left_delayed
	.BYTE $04, $78, $58, objects_blaster_left_delayed
	.BYTE $04, $98, $38, objects_blaster_left
	.BYTE $04, $D8, $98, objects_blaster_left_delayed
	.BYTE $05, $48, $B8, objects_blaster_right_delayed
	.BYTE $05, $78, $78, objects_blaster_left_delayed
	.BYTE $05, $B8, $38, objects_blaster_left
	.BYTE $06, $78, $D8, objects_blaster_right_delayed
	.BYTE $06, $98, $28, objects_blaster_left_delayed
	.BYTE $06, $B8, $58, objects_blaster_left
	.BYTE $07, $90, $B4, objects_super_cutter_standby
	.BYTE $08, $38, $B8, objects_kamadoma
	.BYTE $08, $58, $98, objects_kamadoma
	.BYTE $08, $78, $78, objects_kamadoma
	.BYTE $09, $48, $A8, objects_adhering_suzy_vertical
	.BYTE $09, $68, $68, objects_adhering_suzy_vertical
	.BYTE $09, $B8, $88, objects_adhering_suzy_horizontal
	.BYTE $0A, $48, $48, objects_adhering_suzy_horizontal
	.BYTE $0A, $58, $88, objects_adhering_suzy_vertical
	.BYTE $0A, $78, $68, objects_adhering_suzy_horizontal
	.BYTE $0A, $D8, $88, objects_adhering_suzy_horizontal
	.BYTE $0B, $78, $A8, objects_adhering_suzy_horizontal
	.BYTE $0B, $88, $B8, objects_adhering_suzy_vertical
	.BYTE $0B, $B8, $68, objects_adhering_suzy_horizontal
	.BYTE $0B, $D8, $48, objects_adhering_suzy_horizontal
	.BYTE $0C, $28, $48, objects_adhering_suzy_horizontal
	.BYTE $0C, $38, $78, objects_adhering_suzy_vertical
	.BYTE $0C, $38, $A8, objects_adhering_suzy_horizontal
	.BYTE $0C, $88, $88, objects_adhering_suzy_horizontal
	.BYTE $0C, $C8, $28, objects_adhering_suzy_vertical
	.BYTE $0D, $90, $B4, objects_super_cutter_standby
	.BYTE $0F, $28, $B8, objects_large_life_capsule
	.BYTE $0F, $60, $4C, objects_bunby_heli
	.BYTE $0F, $90, $8C, objects_bunby_heli
	.BYTE $0F, $A0, $5C, objects_bunby_heli
	.BYTE $10, $F8, $80, objects_mambu
	.BYTE $11, $F8, $80, objects_mambu
	.BYTE $12, $E0, $AC, objects_big_eye
	.BYTE $14, $D8, $A0, objects_screw_driver_ground
	.BYTE $15, $C8, $60, objects_screw_driver_ceiling
	.BYTE $16, $50, $A0, objects_screw_driver_ground
	.BYTE objects_set_end
