;objects move delay
	.BYTE $00 ;objects_bunby_heli
	.BYTE $1F ;objects_metall
	.BYTE $01 ;objects_kamadoma
	.BYTE $00 ;objects_gabyoall
	.BYTE $00 ;objects_adhering_suzy_vertical
	.BYTE $00 ;objects_screw_driver_ground
	.BYTE $00 ;objects_watcher
	.BYTE $00 ;objects_pepe
	.BYTE $00 ;objects_killer_bomb
	.BYTE $0F ;objects_big_eye
	.BYTE $00 ;objects_mambu
	.BYTE $00 ;objects_blaster_left_delayed
	.BYTE $3F ;objects_thrower_delayed
	.BYTE $01 ;objects_bombombomb
	.BYTE $00 ;objects_fireball
	.BYTE $10 ;objects_flame_pillar
	.BYTE $BB ;objects_appearing_block_generator
	.BYTE $00 ;objects_super_cutter
	.BYTE $20 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $00 ;objects_crazy_razy
	.BYTE $20 ;objects_pickelman
	.BYTE $00 ;objects_screw_driver_ceiling
	.BYTE $00 ;objects_blaster_right_delayed
	.BYTE $00 ;objects_fireball_standby
	.BYTE $01 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $00 ;objects_super_cutter_standby
	.BYTE $00 ;objects_crazy_razy_head_1
	.BYTE $00 ;objects_crazy_razy_foot_1
	.BYTE $00 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $00 ;objects_adhering_suzy_horizontal
	.BYTE $26 ;objects_blaster_left
	.BYTE $26 ;objects_blaster_right
	.BYTE $20 ;objects_thrower
	.BYTE $3F ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $00 ;objects_crazy_razy_foot_2
	.BYTE $00 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f
	.BYTE $00 ;objects_30
	.BYTE $18 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $00 ;objects_cwu_01p
	.BYTE $00 ;objects_3b
	.BYTE $00 ;objects_score_ball
	.BYTE $00 ;objects_small_weapon_capsule
	.BYTE $00 ;objects_small_life_capsule
	.BYTE $00 ;objects_large_weapon_capsule
	.BYTE $00 ;objects_large_life_capsule
	.BYTE $00 ;objects_1up
	.BYTE $00 ;objects_magnet_beam
	.BYTE $00 ;objects_teleport
	.BYTE $00 ;objects_heart_part
	.BYTE $00 ;objects_yashichi
