score_table:
;score = x * 100, x is decimal without $
;example, kill big eye, score = 90 * 100 = 9000 instead $9000
	.BYTE $05 ;objects_bunby_heli
	.BYTE $05 ;objects_metall
	.BYTE $03 ;objects_kamadoma
	.BYTE $02 ;objects_gabyoall
	.BYTE $03 ;objects_adhering_suzy_vertical
	.BYTE $05 ;objects_screw_driver_ground
	.BYTE $08 ;objects_watcher
	.BYTE $05 ;objects_pepe
	.BYTE $08 ;objects_killer_bomb
	.BYTE $90 ;objects_big_eye
	.BYTE $08 ;objects_mambu
	.BYTE $02 ;objects_blaster_left_delayed
	.BYTE $03 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $03 ;objects_fireball
	.BYTE $05 ;objects_flame_pillar
	.BYTE $08 ;objects_appearing_block_generator
	.BYTE $15 ;objects_super_cutter
	.BYTE $50 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $05 ;objects_crazy_razy
	.BYTE $15 ;objects_pickelman
	.BYTE $05 ;objects_screw_driver_ceiling
	.BYTE $02 ;objects_blaster_right_delayed
	.BYTE $03 ;objects_fireball_standby
	.BYTE $03 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $15 ;objects_super_cutter_standby
	.BYTE $05 ;objects_crazy_razy_head_1
	.BYTE $05 ;objects_crazy_razy_foot_1
	.BYTE $05 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $03 ;objects_adhering_suzy_horizontal
	.BYTE $02 ;objects_blaster_left
	.BYTE $02 ;objects_blaster_right
	.BYTE $03 ;objects_thrower
	.BYTE $03 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $08 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $05 ;objects_crazy_razy_foot_2
	.BYTE $04 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $02 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $00 ;objects_cwu_01p
