mega_buster_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $00 ;objects_gabyoall
	.BYTE $04 ;objects_adhering_suzy_vertical
	.BYTE $07 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $01 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $04 ;objects_super_cutter
	.BYTE $02 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $07 ;objects_crazy_razy
	.BYTE $02 ;objects_pickelman
	.BYTE $07 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $02 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $07 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $04 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $04 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $02 ;objects_cwu_01p

rolling_cutter_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $14 ;objects_gabyoall
	.BYTE $14 ;objects_adhering_suzy_vertical
	.BYTE $14 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $01 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $04 ;objects_super_cutter
	.BYTE $04 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $07 ;objects_crazy_razy
	.BYTE $02 ;objects_pickelman
	.BYTE $14 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $02 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $07 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $14 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $04 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $02 ;objects_cwu_01p

ice_slasher_damage_table:
	.BYTE $00 ;objects_bunby_heli
	.BYTE $00 ;objects_metall
	.BYTE $00 ;objects_kamadoma
	.BYTE $00 ;objects_gabyoall
	.BYTE $00 ;objects_adhering_suzy_vertical
	.BYTE $00 ;objects_screw_driver_ground
	.BYTE $00 ;objects_watcher
	.BYTE $00 ;objects_pepe
	.BYTE $00 ;objects_killer_bomb
	.BYTE $00 ;objects_big_eye
	.BYTE $00 ;objects_mambu
	.BYTE $00 ;objects_blaster_left_delayed
	.BYTE $00 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $00 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $00 ;objects_appearing_block_generator
	.BYTE $00 ;objects_super_cutter
	.BYTE $00 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $00 ;objects_crazy_razy
	.BYTE $00 ;objects_pickelman
	.BYTE $00 ;objects_screw_driver_ceiling
	.BYTE $00 ;objects_blaster_right_delayed
	.BYTE $00 ;objects_fireball_standby
	.BYTE $00 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $00 ;objects_super_cutter_standby
	.BYTE $00 ;objects_crazy_razy_head_1
	.BYTE $00 ;objects_crazy_razy_foot_1
	.BYTE $00 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $00 ;objects_adhering_suzy_horizontal
	.BYTE $00 ;objects_blaster_left
	.BYTE $00 ;objects_blaster_right
	.BYTE $00 ;objects_thrower
	.BYTE $00 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $00 ;objects_crazy_razy_foot_2
	.BYTE $00 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $00 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $00 ;objects_cwu_01p

hyper_bomb_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $14 ;objects_gabyoall
	.BYTE $14 ;objects_adhering_suzy_vertical
	.BYTE $14 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $04 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $14 ;objects_super_cutter
	.BYTE $14 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $14 ;objects_crazy_razy
	.BYTE $14 ;objects_pickelman
	.BYTE $14 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $14 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $14 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $14 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $14 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $07 ;objects_cwu_01p

fire_storm_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $14 ;objects_gabyoall
	.BYTE $14 ;objects_adhering_suzy_vertical
	.BYTE $14 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $01 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $04 ;objects_super_cutter
	.BYTE $04 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $14 ;objects_crazy_razy
	.BYTE $14 ;objects_pickelman
	.BYTE $14 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $02 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $14 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $14 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $14 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $02 ;objects_cwu_01p

thunder_beam_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $14 ;objects_gabyoall
	.BYTE $14 ;objects_adhering_suzy_vertical
	.BYTE $14 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $04 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $02 ;objects_super_cutter
	.BYTE $07 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $14 ;objects_crazy_razy
	.BYTE $04 ;objects_pickelman
	.BYTE $14 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $01 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $14 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $14 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $14 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $04 ;objects_cwu_01p

super_arm_damage_table:
	.BYTE $14 ;objects_bunby_heli
	.BYTE $14 ;objects_metall
	.BYTE $14 ;objects_kamadoma
	.BYTE $14 ;objects_gabyoall
	.BYTE $14 ;objects_adhering_suzy_vertical
	.BYTE $14 ;objects_screw_driver_ground
	.BYTE $14 ;objects_watcher
	.BYTE $14 ;objects_pepe
	.BYTE $14 ;objects_killer_bomb
	.BYTE $07 ;objects_big_eye
	.BYTE $14 ;objects_mambu
	.BYTE $14 ;objects_blaster_left_delayed
	.BYTE $14 ;objects_thrower_delayed
	.BYTE $00 ;objects_bombombomb
	.BYTE $14 ;objects_fireball
	.BYTE $00 ;objects_flame_pillar
	.BYTE $14 ;objects_appearing_block_generator
	.BYTE $14 ;objects_super_cutter
	.BYTE $14 ;objects_sniper_joe
	.BYTE $00 ;objects_foot_holder
	.BYTE $14 ;objects_crazy_razy
	.BYTE $14 ;objects_pickelman
	.BYTE $14 ;objects_screw_driver_ceiling
	.BYTE $14 ;objects_blaster_right_delayed
	.BYTE $14 ;objects_fireball_standby
	.BYTE $14 ;objects_short_elec_beam
	.BYTE $00 ;objects_enemies_bullet_palette_2
	.BYTE $00 ;objects_enemies_killed
	.BYTE $14 ;objects_super_cutter_standby
	.BYTE $14 ;objects_crazy_razy_head_1
	.BYTE $14 ;objects_crazy_razy_foot_1
	.BYTE $14 ;objects_crazy_razy_head_2
	.BYTE $00 ;objects_crazy_razy_hit
	.BYTE $14 ;objects_adhering_suzy_horizontal
	.BYTE $14 ;objects_blaster_left
	.BYTE $14 ;objects_blaster_right
	.BYTE $14 ;objects_thrower
	.BYTE $14 ;objects_short_elec_beam_delayed
	.BYTE $00 ;objects_bombombomb_cluster
	.BYTE $00 ;objects_appearing_block
	.BYTE $00 ;objects_bomb_explosion_cluster
	.BYTE $14 ;objects_crazy_razy_foot_2
	.BYTE $14 ;objects_watcher_move
	.BYTE $00 ;objects_watcher_elec_thrower
	.BYTE $00 ;objects_track_platform
	.BYTE $00 ;objects_enemies_bullet_palette_3
	.BYTE $00 ;objects_pickaxe
	.BYTE $00 ;objects_2f, gutsman is used for enable track platform sfx, wily3 is used for enable flood
	.BYTE $00 ;objects_30, gutsman is used for disable track platform sfx, wily3 is used for palette change
	.BYTE $14 ;objects_changkey
	.BYTE $00 ;objects_fireman_palette_alternate
	.BYTE $00 ;objects_copy_robot_rolling_cutter
	.BYTE $00 ;objects_copy_robot_ice_slasher
	.BYTE $00 ;objects_copy_robot_hyper_bomb
	.BYTE $00 ;objects_copy_robot_fire_storm_flame
	.BYTE $00 ;objects_copy_robot_fire_storm_shield
	.BYTE $00 ;objects_yellow_devil_parts
	.BYTE $00 ;objects_yellow_devil_1
	.BYTE $14 ;objects_cwu_01p

boss_damage_table:
;mega buster, rolling cutter, ice slasher, hyper bomb, fire storm, thunder beam, super arm, magnet beam
	.BYTE 3,  1, 0,  2, 3,  1, 14, 0 ;cutman
	.BYTE 1,  2, 0,  4, 1, 10,  0, 0 ;iceman
	.BYTE 2,  2, 0,  1, 4,  2,  0, 0 ;bombman
	.BYTE 2,  2, 4,  1, 1,  1,  0, 0 ;fireman
	.BYTE 1, 10, 0,  2, 1,  1,  4, 0 ;elecman
	.BYTE 2,  1, 0, 10, 2,  1,  1, 0 ;gutsman
	.BYTE 2,  2, 0,  0, 2,  4,  0, 0 ;yellow devil
	.BYTE 1,  1, 0,  2, 2,  2,  0, 0 ;copy robot
	.BYTE 0,  0, 0,  0, 0,  0,  0, 0 ;cwu01p
	.BYTE 1,  1, 1,  1, 4,  1,  1, 0 ;wily machine 1 phase 1
	.BYTE 1,  1, 0,  1, 1,  1,  1, 0 ;wily machine 1 phase 2
	.BYTE 0,  0, 0,  0, 0,  0,  0, 0 ;usused
