;fireman screen id set
	.BYTE $00
	.BYTE $01
	.BYTE $02
	.BYTE $03
	.BYTE $04
	.BYTE $05
	.BYTE $06
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $0B
	.BYTE $0C
	.BYTE $01
	.BYTE $0D
	.BYTE $0E
	.BYTE $0F
	.BYTE $0F
	.BYTE $10
	.BYTE $11

;wily4 screen id set
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $15
	.BYTE $17
	.BYTE $18
	.BYTE $19
	.BYTE $1A
	.BYTE $1A
	.BYTE $1A
	.BYTE $1A
	.BYTE $1B
	.BYTE $1C
	.BYTE $1D
	.BYTE $1D

;end
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF

;screen id pointers
	.WORD mapset_fireman_wily4_00
	.WORD mapset_fireman_wily4_01
	.WORD mapset_fireman_wily4_02
	.WORD mapset_fireman_wily4_03
	.WORD mapset_fireman_wily4_04
	.WORD mapset_fireman_wily4_05
	.WORD mapset_fireman_wily4_06
	.WORD mapset_fireman_wily4_07
	.WORD mapset_fireman_wily4_08
	.WORD mapset_fireman_wily4_09
	.WORD mapset_fireman_wily4_0a
	.WORD mapset_fireman_wily4_0b
	.WORD mapset_fireman_wily4_0c
	.WORD mapset_fireman_wily4_0d
	.WORD mapset_fireman_wily4_0e
	.WORD mapset_fireman_wily4_0f
	.WORD mapset_fireman_wily4_10
	.WORD mapset_fireman_wily4_11
	.WORD mapset_fireman_wily4_12
	.WORD mapset_fireman_wily4_13
	.WORD mapset_fireman_wily4_14
	.WORD mapset_fireman_wily4_15
	.WORD mapset_fireman_wily4_16
	.WORD mapset_fireman_wily4_17
	.WORD mapset_fireman_wily4_18
	.WORD mapset_fireman_wily4_19
	.WORD mapset_fireman_wily4_1a
	.WORD mapset_fireman_wily4_1b
	.WORD mapset_fireman_wily4_1c
	.WORD mapset_fireman_wily4_1d
	.WORD mapset_fireman_wily4_1e
	.WORD mapset_fireman_wily4_1f
