base $8000
;incsrc audio.asm
pad $9a60
incsrc track_data_pointers.asm
pad $9ac6
incsrc .\music\all_stage_clear.asm
incsrc .\music\stage_select.asm
incsrc .\music\game_start.asm
incsrc .\music\game_over.asm
incsrc .\music\stage_clear.asm
incsrc .\music\cut.asm
;incsrc .\music\fire.asm
;incsrc .\music\bomb.asm
;incsrc .\music\elec.asm
;incsrc .\music\guts.asm
;incsrc .\music\wily_boss.asm
;incsrc .\music\wily1.asm
;incsrc .\music\boss.asm
;incsrc .\music\ending.asm
;incsrc .\music\ice.asm
;incsrc .\music\wily3.asm
;incsrc .\sfx\ufo.asm
;incsrc .\sfx\defeat_boss.asm
;incsrc .\sfx\magnet_beam.asm
;incsrc .\sfx\shoot.asm
;incsrc .\sfx\enemy_shoot.asm
;incsrc .\sfx\damage_mm.asm
;incsrc .\sfx\block_scatter.asm
;incsrc .\sfx\health_bar.asm
;incsrc .\sfx\landing.asm
;incsrc .\sfx\gain_ball.asm
;incsrc .\sfx\destroy_enemy.asm
;incsrc .\sfx\select_robo.asm
;incsrc .\sfx\shoot_recoil.asm
;incsrc .\sfx\thunder_beam.asm
;incsrc .\sfx\change_weapon.asm
;incsrc .\sfx\teleport_in.asm
;incsrc .\sfx\score.asm
;incsrc .\sfx\open_menu.asm
;incsrc .\sfx\lift.asm
;incsrc .\sfx\boss_door.asm
;incsrc .\sfx\rolling_cutter.asm
;incsrc .\sfx\cutman.asm
;incsrc .\unused\unused27.asm
;incsrc .\sfx\earthquake.asm
;incsrc .\sfx\bigeye.asm
;incsrc .\sfx\ice_slasher.asm
;incsrc .\sfx\water.asm
;incsrc .\sfx\yoku_block.asm
;incsrc .\sfx\fireman_storm.asm
;incsrc .\sfx\fire_storm.asm
;incsrc .\unused\unused2f.asm
;incsrc .\sfx\flood.asm
;incsrc .\sfx\death.asm
;incsrc .\sfx\1up.asm
;incsrc .\unused\unusedpre.asm
pad $c000