track_pointers:
	.WORD music_wily_defeated
	.WORD music_stage_select
	.WORD music_boss_show
	.WORD music_game_over
	.WORD music_boss_defeated
	.WORD music_cutman
	.WORD music_fireman
	.WORD music_fireman
	.WORD music_bombman
	.WORD music_elecman
	.WORD music_gutsman
	.WORD music_wily_boss_fighting
	.WORD music_wily1_2
	.WORD music_boss_fighting
	.WORD music_ending
	.WORD music_iceman
	.WORD music_wily3_4
	.WORD sfx_wily_ufo
	.WORD sfx_explosion
	.WORD sfx_magnet_beam
	.WORD sfx_mega_buster
	.WORD sfx_enemy_bullet
	.WORD sfx_megaman_hit
	.WORD sfx_throw_boulder
	.WORD sfx_refill
	.WORD sfx_landing
	.WORD sfx_pickup_ball
	.WORD sfx_enemy_hit
	.WORD sfx_press_start
	.WORD sfx_enemy_immune
	.WORD sfx_thunder_beam
	.WORD sfx_select
	.WORD sfx_teleport
	.WORD sfx_points
	.WORD sfx_pause
	.WORD sfx_track_platform
	.WORD sfx_door
	.WORD sfx_rolling_cutter
	.WORD sfx_cutman_move
	.WORD sfx_27
	.WORD sfx_earthquake
	.WORD sfx_big_eye
	.WORD sfx_ice_slasher
	.WORD sfx_jump_into_water
	.WORD sfx_appearing_block
	.WORD sfx_fireman_move
	.WORD sfx_fire_storm
	.WORD sfx_2f
	.WORD sfx_flood
	.WORD sfx_megaman_death
	.WORD sfx_1up
