;music
	dw music_all_stage_clear
	dw music_stage_select
	dw music_game_start
	dw music_game_over
	dw music_stage_clear
	;dw music_cut
	;dw music_fire
	;dw music_fire
	;dw music_bomb
	;dw music_elec
	;dw music_guts
	;dw music_wily_boss
	;dw music_wily1
	;dw music_boss
	;dw music_ending
	;dw music_ice
	;dw music_wily3

;sfx
	;dw sfx_ufo
	;dw sfx_defeat_boss
	;dw sfx_magnet_beam
	;dw sfx_shoot
	;dw sfx_enemy_shoot
	;dw sfx_damage_mm
	;dw sfx_block_scatter
	;dw sfx_health_bar
	;dw sfx_landing
	;dw sfx_gain_ball
	;dw sfx_destroy_enemy
	;dw sfx_select_robo
	;dw sfx_shoot_recoil
	;dw sfx_thunder_beam
	;dw sfx_change_weapon
	;dw sfx_teleport_in
	;dw sfx_score
	;dw sfx_open_menu
	;dw sfx_lift
	;dw sfx_boss_door
	;dw sfx_rolling_cutter
	;dw sfx_cutman
	;dw sfx_unused27
	;dw sfx_earthquake
	;dw sfx_bigeye
	;dw sfx_ice_slasher
	;dw sfx_water
	;dw sfx_yoku_block
	;dw sfx_fireman_storm
	;dw sfx_fire_storm
	;dw sfx_unused2f
	;dw sfx_flood
	;dw sfx_death
	;dw sfx_1up