;elecman screen id set
	.BYTE $00
	.BYTE $01
	.BYTE $01
	.BYTE $02
	.BYTE $02
	.BYTE $03
	.BYTE $04
	.BYTE $05
	.BYTE $06
	.BYTE $07
	.BYTE $08
	.BYTE $09
	.BYTE $0A
	.BYTE $10
	.BYTE $11
	.BYTE $12
	.BYTE $05
	.BYTE $06
	.BYTE $0B
	.BYTE $0C
	.BYTE $0D
	.BYTE $0E
	.BYTE $0E
	.BYTE $0F

;unknown screen id set
	.BYTE $10
	.BYTE $11
	.BYTE $12
	.BYTE $12
	.BYTE $13
	.BYTE $14
	.BYTE $15
	.BYTE $16
	.BYTE $17
	.BYTE $18

;end
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF
	.BYTE $FF

;screen id pointers
	.WORD mapset_elecman_00
	.WORD mapset_elecman_01
	.WORD mapset_elecman_02
	.WORD mapset_elecman_03
	.WORD mapset_elecman_04
	.WORD mapset_elecman_05
	.WORD mapset_elecman_06
	.WORD mapset_elecman_07
	.WORD mapset_elecman_08
	.WORD mapset_elecman_09
	.WORD mapset_elecman_0a
	.WORD mapset_elecman_0b
	.WORD mapset_elecman_0c
	.WORD mapset_elecman_0d
	.WORD mapset_elecman_0e
	.WORD mapset_elecman_0f
	.WORD mapset_elecman_10
	.WORD mapset_elecman_11
	.WORD mapset_elecman_12
	.WORD mapset_elecman_13
	.WORD mapset_elecman_14
	.WORD mapset_elecman_15
	.WORD mapset_elecman_16
	.WORD mapset_elecman_17
	.WORD mapset_elecman_18
	.WORD mapset_elecman_19
	.WORD mapset_elecman_1a
	.WORD mapset_elecman_1b
	.WORD mapset_elecman_1c
	.WORD mapset_elecman_1d
	.WORD mapset_elecman_1e
	.WORD mapset_elecman_1f
