objects_set_iceman:
	;      id,   x,   y, object
	.BYTE $01, $00, $B4, objects_crazy_razy
	.BYTE $02, $30, $94, objects_crazy_razy
	.BYTE $02, $B0, $74, objects_crazy_razy
	.BYTE $03, $30, $54, objects_crazy_razy
	.BYTE $04, $80, $02, objects_spawn_tiles
	.BYTE $04, $82, $FE, objects_crazy_razy_head_2
	.BYTE $04, $98, $BC, objects_gabyoall
	.BYTE $04, $F0, $90, objects_pepe
	.BYTE $05, $98, $BC, objects_gabyoall
	.BYTE $06, $98, $BC, objects_gabyoall
	.BYTE $07, $78, $9C, objects_gabyoall
	.BYTE $08, $00, $00, objects_spawn_tiles
	.BYTE $08, $80, $FE, objects_pepe
	.BYTE $09, $08, $C8, objects_large_life_capsule
	.BYTE $09, $28, $C8, objects_adhering_suzy_vertical
	.BYTE $09, $48, $A8, objects_adhering_suzy_vertical
	.BYTE $0A, $B8, $DC, objects_gabyoall
	.BYTE $0A, $E0, $80, objects_appearing_block_generator
	.BYTE $0B, $98, $DC, objects_gabyoall
	.BYTE $0B, $E0, $80, objects_appearing_block_generator
	.BYTE $0D, $4C, $54, objects_foot_holder
	.BYTE $0D, $A4, $9C, objects_foot_holder
	.BYTE $0D, $F4, $9C, objects_foot_holder
	.BYTE $0E, $64, $B4, objects_foot_holder
	.BYTE $0E, $90, $98, objects_large_weapon_capsule
	.BYTE $0E, $EC, $9C, objects_foot_holder
	.BYTE $0F, $4C, $AC, objects_foot_holder
	.BYTE $0F, $70, $70, objects_pepe
	.BYTE $0F, $A4, $84, objects_foot_holder
	.BYTE $0F, $F4, $9C, objects_foot_holder
	.BYTE $10, $01, $FE, objects_pepe
	.BYTE $10, $48, $C8, objects_1up
	.BYTE $11, $30, $7C, objects_small_weapon_capsule
	.BYTE $11, $48, $7C, objects_small_weapon_capsule
	.BYTE $11, $60, $7C, objects_small_weapon_capsule
	.BYTE $11, $78, $79, objects_small_life_capsule
	.BYTE $11, $90, $79, objects_small_life_capsule
	.BYTE $11, $A8, $79, objects_small_life_capsule
	.BYTE $12, $E0, $AC, objects_big_eye
	.BYTE $14, $F0, $A0, objects_pepe
	.BYTE $16, $E0, $FE, objects_pepe
	.BYTE objects_set_end
