wily2_objects_set:
	;      id,   x,   y, object
	.BYTE $19, $10, $4C, objects_bunby_heli
	.BYTE $19, $40, $8C, objects_bunby_heli
	.BYTE $19, $50, $5C, objects_bunby_heli
	.BYTE $19, $C8, $A8, objects_small_life_capsule
	.BYTE $19, $F0, $4C, objects_bunby_heli
	.BYTE $1A, $20, $8C, objects_bunby_heli
	.BYTE $1A, $30, $5C, objects_bunby_heli
	.BYTE $1A, $F0, $4C, objects_bunby_heli
	.BYTE $1B, $20, $8C, objects_bunby_heli
	.BYTE $1B, $30, $5C, objects_bunby_heli
	.BYTE $1B, $C8, $BC, objects_small_weapon_capsule
	.BYTE $1B, $D8, $BC, objects_small_weapon_capsule
	.BYTE $1C, $80, $80, objects_3b
	.BYTE $1D, $C8, $A8, objects_small_life_capsule
	.BYTE $1D, $D8, $B0, objects_screw_driver_ground
	.BYTE $1E, $D8, $B0, objects_screw_driver_ground
	.BYTE $1F, $C8, $BC, objects_small_weapon_capsule
	.BYTE $1F, $D8, $BC, objects_small_weapon_capsule
	.BYTE $20, $80, $80, objects_3b
	.BYTE $21, $78, $E0, objects_bombombomb
	.BYTE $21, $C8, $AC, objects_small_weapon_capsule
	.BYTE $21, $F8, $E0, objects_bombombomb
	.BYTE $22, $68, $E0, objects_bombombomb
	.BYTE $22, $C8, $AC, objects_small_weapon_capsule
	.BYTE $22, $E8, $E0, objects_bombombomb
	.BYTE $24, $28, $28, objects_1up
	.BYTE $24, $A8, $58, objects_adhering_suzy_vertical
	.BYTE $24, $C8, $88, objects_adhering_suzy_vertical
	.BYTE $24, $D0, $B8, objects_adhering_suzy_horizontal
	.BYTE $25, $D8, $78, objects_adhering_suzy_horizontal
	.BYTE $25, $D8, $88, objects_adhering_suzy_horizontal
	.BYTE $25, $D8, $B8, objects_adhering_suzy_vertical
	.BYTE $26, $88, $B8, objects_adhering_suzy_horizontal
	.BYTE $26, $D0, $A8, objects_adhering_suzy_horizontal
	.BYTE $26, $D8, $C8, objects_adhering_suzy_horizontal
	.BYTE $27, $28, $78, objects_large_weapon_capsule
	.BYTE $27, $D8, $48, objects_blaster_left_delayed
	.BYTE $27, $D8, $68, objects_blaster_left
	.BYTE $27, $D8, $88, objects_blaster_left_delayed
	.BYTE $27, $D8, $A8, objects_blaster_left
	.BYTE $28, $48, $88, objects_blaster_right_delayed
	.BYTE $28, $88, $38, objects_adhering_suzy_horizontal
	.BYTE $28, $D8, $48, objects_adhering_suzy_horizontal
	.BYTE $28, $D8, $98, objects_adhering_suzy_horizontal
	.BYTE objects_set_end
