;oam sprites set pointers
	.WORD oam_enemies_sprites_00
	.WORD oam_enemies_sprites_01
	.WORD oam_enemies_sprites_02
	.WORD oam_enemies_sprites_03
	.WORD oam_enemies_sprites_04
	.WORD oam_enemies_sprites_05
	.WORD oam_enemies_sprites_06
	.WORD oam_enemies_sprites_07
	.WORD oam_enemies_sprites_08
	.WORD oam_enemies_sprites_09
	.WORD oam_enemies_sprites_0a
	.WORD oam_enemies_sprites_0b
	.WORD oam_enemies_sprites_0c
	.WORD oam_enemies_sprites_0d
	.WORD oam_enemies_sprites_0e
	.WORD oam_enemies_sprites_0f
	.WORD oam_enemies_sprites_10
	.WORD oam_enemies_sprites_11
	.WORD oam_enemies_sprites_12
	.WORD oam_enemies_sprites_13
	.WORD oam_enemies_sprites_14
	.WORD oam_enemies_sprites_15
	.WORD oam_enemies_sprites_16
	.WORD oam_enemies_sprites_17
	.WORD oam_enemies_sprites_18
	.WORD oam_enemies_sprites_19
	.WORD oam_enemies_sprites_1a
	.WORD oam_enemies_sprites_1b
	.WORD oam_enemies_sprites_1c
	.WORD oam_enemies_sprites_1d
	.WORD oam_enemies_sprites_1e
	.WORD oam_enemies_sprites_1f
	.WORD oam_enemies_sprites_20
	.WORD oam_enemies_sprites_21
	.WORD oam_enemies_sprites_22
	.WORD oam_enemies_sprites_23
	.WORD oam_enemies_sprites_24
	.WORD oam_enemies_sprites_25
	.WORD oam_enemies_sprites_26
	.WORD oam_enemies_sprites_27
	.WORD oam_enemies_sprites_28
	.WORD oam_enemies_sprites_29
	.WORD oam_enemies_sprites_2a
	.WORD oam_enemies_sprites_2b
	.WORD oam_enemies_sprites_2c
	.WORD oam_enemies_sprites_2d
	.WORD oam_enemies_sprites_2e
	.WORD oam_enemies_sprites_2f
	.WORD oam_enemies_sprites_30
	.WORD oam_enemies_sprites_31
	.WORD oam_enemies_sprites_32
	.WORD oam_enemies_sprites_33
	.WORD oam_enemies_sprites_34
	.WORD oam_enemies_sprites_35
	.WORD oam_enemies_sprites_36
	.WORD oam_enemies_sprites_37
	.WORD oam_enemies_sprites_38
	.WORD oam_enemies_sprites_39
	.WORD oam_enemies_sprites_3a
	.WORD oam_enemies_sprites_3b
	.WORD oam_enemies_sprites_3c
	.WORD oam_enemies_sprites_3d
	.WORD oam_enemies_sprites_3e
	.WORD oam_enemies_sprites_3f
	.WORD oam_enemies_sprites_40
	.WORD oam_enemies_sprites_41
	.WORD oam_enemies_sprites_42
	.WORD oam_enemies_sprites_43
	.WORD oam_enemies_sprites_44
	.WORD oam_enemies_sprites_45
	.WORD oam_enemies_sprites_46
	.WORD oam_enemies_sprites_47
	.WORD oam_enemies_sprites_48
	.WORD oam_enemies_sprites_49
	.WORD oam_enemies_sprites_4a
	.WORD oam_enemies_sprites_4b
	.WORD oam_enemies_sprites_4c
	.WORD oam_enemies_sprites_4d
	.WORD oam_enemies_sprites_4e
	.WORD oam_enemies_sprites_4f
	.WORD oam_enemies_sprites_50
	.WORD oam_enemies_sprites_51
	.WORD oam_enemies_sprites_52
	.WORD oam_enemies_sprites_53
	.WORD oam_enemies_sprites_54
	.WORD oam_enemies_sprites_55
	.WORD oam_enemies_sprites_56
	.WORD oam_enemies_sprites_57
	.WORD oam_enemies_sprites_58
	.WORD oam_enemies_sprites_59
	.WORD oam_enemies_sprites_5a
	.WORD oam_enemies_sprites_5b
	.WORD oam_enemies_sprites_5c
	.WORD oam_enemies_sprites_5d
	.WORD oam_enemies_sprites_5e
	.WORD oam_enemies_sprites_5f
	.WORD oam_enemies_sprites_60
	.WORD oam_enemies_sprites_61
	.WORD oam_enemies_sprites_62
	.WORD oam_enemies_sprites_63
	.WORD oam_enemies_sprites_64
	.WORD oam_enemies_sprites_65
	.WORD oam_enemies_sprites_66
	.WORD oam_enemies_sprites_67
	.WORD oam_enemies_sprites_68
	.WORD oam_enemies_sprites_69
	.WORD oam_enemies_sprites_6a
	.WORD oam_enemies_sprites_6b
	.WORD oam_enemies_sprites_6c
	.WORD oam_enemies_sprites_6d
	.WORD oam_enemies_sprites_6e
	.WORD oam_enemies_sprites_6f
	.WORD oam_enemies_sprites_70
	.WORD oam_enemies_sprites_71
	.WORD oam_enemies_sprites_72
	.WORD oam_enemies_sprites_73
	.WORD oam_enemies_sprites_74
	.WORD oam_enemies_sprites_75
	.WORD oam_enemies_sprites_76
	.WORD oam_enemies_sprites_77
	.WORD oam_enemies_sprites_78
	.WORD oam_enemies_sprites_79
	.WORD oam_enemies_sprites_7a
	.WORD oam_enemies_sprites_7b
	.WORD oam_enemies_sprites_7c
	.WORD oam_enemies_sprites_7d
	.WORD oam_enemies_sprites_7e
	.WORD oam_enemies_sprites_7f
	.WORD oam_enemies_sprites_80
	.WORD oam_enemies_sprites_81
	.WORD oam_enemies_sprites_82
	.WORD oam_enemies_sprites_83
	.WORD oam_enemies_sprites_84
	.WORD oam_enemies_sprites_85
	.WORD oam_enemies_sprites_86
	.WORD oam_enemies_sprites_87
	.WORD oam_enemies_sprites_88
	.WORD oam_enemies_sprites_89
	.WORD oam_enemies_sprites_8a
	.WORD oam_enemies_sprites_8b
	.WORD oam_enemies_sprites_8c
	.WORD oam_enemies_sprites_8d
	.WORD oam_enemies_sprites_8e
	.WORD oam_enemies_sprites_8f
