;oam sprites set pointers
	.WORD oam_sprites_00
	.WORD oam_sprites_01
	.WORD oam_sprites_02
	.WORD oam_sprites_03
	.WORD oam_sprites_04
	.WORD oam_sprites_05
	.WORD oam_sprites_06
	.WORD oam_sprites_07
	.WORD oam_sprites_08
	.WORD oam_sprites_09
	.WORD oam_sprites_0a
	.WORD oam_sprites_0b
	.WORD oam_sprites_0c
	.WORD oam_sprites_0d
	.WORD oam_sprites_0e
	.WORD oam_sprites_0f
	.WORD oam_sprites_10
	.WORD oam_sprites_11
	.WORD oam_sprites_12
	.WORD oam_sprites_13
	.WORD oam_sprites_14
	.WORD oam_sprites_15
	.WORD oam_sprites_16
	.WORD oam_sprites_17
	.WORD oam_sprites_18
	.WORD oam_sprites_19
	.WORD oam_sprites_1a
	.WORD oam_sprites_1b
	.WORD oam_sprites_1c
	.WORD oam_sprites_1d
	.WORD oam_sprites_1e
	.WORD oam_sprites_1f
	.WORD oam_sprites_20
	.WORD oam_sprites_21
	.WORD oam_sprites_22
	.WORD oam_sprites_23
	.WORD oam_sprites_24
	.WORD oam_sprites_25
	.WORD oam_sprites_26
	.WORD oam_sprites_27
	.WORD oam_sprites_28
	.WORD oam_sprites_29
	.WORD oam_sprites_2a
	.WORD oam_sprites_2b
	.WORD oam_sprites_2c
	.WORD oam_sprites_2d
	.WORD oam_sprites_2e
	.WORD oam_sprites_2f
	.WORD oam_sprites_30
	.WORD oam_sprites_31
	.WORD oam_sprites_32
	.WORD oam_sprites_33
	.WORD oam_sprites_34
	.WORD oam_sprites_35
	.WORD oam_sprites_36
	.WORD oam_sprites_37
	.WORD oam_sprites_38
	.WORD oam_sprites_39
	.WORD oam_sprites_3a
	.WORD oam_sprites_3b
	.WORD oam_sprites_3c
	.WORD oam_sprites_3d
	.WORD oam_sprites_3e
	.WORD oam_sprites_3f
	.WORD oam_sprites_40
	.WORD oam_sprites_41
	.WORD oam_sprites_42
	.WORD oam_sprites_43
	.WORD oam_sprites_44
	.WORD oam_sprites_45
	.WORD oam_sprites_46
	.WORD oam_sprites_47
	.WORD oam_sprites_48
	.WORD oam_sprites_49
	.WORD oam_sprites_4a
	.WORD oam_sprites_4b
	.WORD oam_sprites_4c
	.WORD oam_sprites_4d
	.WORD oam_sprites_4e
	.WORD oam_sprites_4f
	.WORD oam_sprites_50
	.WORD oam_sprites_51
	.WORD oam_sprites_52
	.WORD oam_sprites_53
	.WORD oam_sprites_54
	.WORD oam_sprites_55
	.WORD oam_sprites_56
	.WORD oam_sprites_57
	.WORD oam_sprites_58
	.WORD oam_sprites_59
	.WORD oam_sprites_5a
	.WORD oam_sprites_5b
	.WORD oam_sprites_5c
	.WORD oam_sprites_5d
	.WORD oam_sprites_5e
	.WORD oam_sprites_5f
	.WORD oam_sprites_60
	.WORD oam_sprites_61
	.WORD oam_sprites_62
	.WORD oam_sprites_63
	.WORD oam_sprites_64
	.WORD oam_sprites_65
	.WORD oam_sprites_66
	.WORD oam_sprites_67
	.WORD oam_sprites_68
	.WORD oam_sprites_69
	.WORD oam_sprites_6a
	.WORD oam_sprites_6b
	.WORD oam_sprites_6c
	.WORD oam_sprites_6d
	.WORD oam_sprites_6e
	.WORD oam_sprites_6f
	.WORD oam_sprites_70
	.WORD oam_sprites_71
	.WORD oam_sprites_72
	.WORD oam_sprites_73
	.WORD oam_sprites_74
	.WORD oam_sprites_75
	.WORD oam_sprites_76
	.WORD oam_sprites_77
	.WORD oam_sprites_78
	.WORD oam_sprites_79
	.WORD oam_sprites_7a
	.WORD oam_sprites_7b
	.WORD oam_sprites_7c
	.WORD oam_sprites_7d
	.WORD oam_sprites_7e
	.WORD oam_sprites_7f
	.WORD oam_sprites_80
	.WORD oam_sprites_81
	.WORD oam_sprites_82
	.WORD oam_sprites_83
	.WORD oam_sprites_84
	.WORD oam_sprites_85
	.WORD oam_sprites_86
	.WORD oam_sprites_87
	.WORD oam_sprites_88
	.WORD oam_sprites_89
	.WORD oam_sprites_8a
	.WORD oam_sprites_8b
	.WORD oam_sprites_8c
	.WORD oam_sprites_8d
	.WORD oam_sprites_8e
	.WORD oam_sprites_8f
	.WORD oam_sprites_90
	.WORD oam_sprites_91
	.WORD oam_sprites_92
	.WORD oam_sprites_93
	.WORD oam_sprites_94
	.WORD oam_sprites_95
	.WORD oam_sprites_96
	.WORD oam_sprites_97
	.WORD oam_sprites_98
	.WORD oam_sprites_99
	.WORD oam_sprites_9a
	.WORD oam_sprites_9b
	.WORD oam_sprites_9c
	.WORD oam_sprites_9d
	.WORD oam_sprites_9e
	.WORD oam_sprites_9f
	.WORD oam_sprites_a0
	.WORD oam_sprites_a1
	.WORD oam_sprites_a2
	.WORD oam_sprites_a3
	.WORD oam_sprites_a4
	.WORD oam_sprites_a5
	.WORD oam_sprites_a6
	.WORD oam_sprites_a7
	.WORD oam_sprites_a8
	.WORD oam_sprites_a9
	.WORD oam_sprites_aa
	.WORD oam_sprites_ab
	.WORD oam_sprites_ac
	.WORD oam_sprites_ad
	.WORD oam_sprites_ae
	.WORD oam_sprites_af
	.WORD oam_sprites_b0
	.WORD oam_sprites_b1
	.WORD oam_sprites_b2
	.WORD oam_sprites_b3
	.WORD oam_sprites_b4
	.WORD oam_sprites_b5
	.WORD oam_sprites_b6
	.WORD oam_sprites_b7
	.WORD oam_sprites_b8
	.WORD oam_sprites_b9
	.WORD oam_sprites_ba
	.WORD oam_sprites_bb
	.WORD oam_sprites_bc
	.WORD oam_sprites_bd
	.WORD oam_sprites_be
	.WORD oam_sprites_bf
	.WORD oam_sprites_c0
	.WORD oam_sprites_c1
	.WORD oam_sprites_c2
