;oam frameset pointers
	.WORD oam_enemies_frameset_00
	.WORD oam_enemies_frameset_01
	.WORD oam_enemies_frameset_02
	.WORD oam_enemies_frameset_03
	.WORD oam_enemies_frameset_04
	.WORD oam_enemies_frameset_05
	.WORD oam_enemies_frameset_06
	.WORD oam_enemies_frameset_07
	.WORD oam_enemies_frameset_08
	.WORD oam_enemies_frameset_09
	.WORD oam_enemies_frameset_0a
	.WORD oam_enemies_frameset_0b
	.WORD oam_enemies_frameset_0c
	.WORD oam_enemies_frameset_0d
	.WORD oam_enemies_frameset_0e
	.WORD oam_enemies_frameset_0f
	.WORD oam_enemies_frameset_10
	.WORD oam_enemies_frameset_11
	.WORD oam_enemies_frameset_12
	.WORD oam_enemies_frameset_13
	.WORD oam_enemies_frameset_14
	.WORD oam_enemies_frameset_15
	.WORD oam_enemies_frameset_16
	.WORD oam_enemies_frameset_17
	.WORD oam_enemies_frameset_18
	.WORD oam_enemies_frameset_19
	.WORD oam_enemies_frameset_1a
	.WORD oam_enemies_frameset_1b
	.WORD oam_enemies_frameset_1c
	.WORD oam_enemies_frameset_1d
	.WORD oam_enemies_frameset_1e
	.WORD oam_enemies_frameset_1f
	.WORD oam_enemies_frameset_20
	.WORD oam_enemies_frameset_21
	.WORD oam_enemies_frameset_22
	.WORD oam_enemies_frameset_23
	.WORD oam_enemies_frameset_24
	.WORD oam_enemies_frameset_25
	.WORD oam_enemies_frameset_26
	.WORD oam_enemies_frameset_27
	.WORD oam_enemies_frameset_28
	.WORD oam_enemies_frameset_29
	.WORD oam_enemies_frameset_2a
	.WORD oam_enemies_frameset_2b
	.WORD oam_enemies_frameset_2c
	.WORD oam_enemies_frameset_2d
	.WORD oam_enemies_frameset_2e
	.WORD oam_enemies_frameset_2f
	.WORD oam_enemies_frameset_30
	.WORD oam_enemies_frameset_31
	.WORD oam_enemies_frameset_32
	.WORD oam_enemies_frameset_33
	.WORD oam_enemies_frameset_34
	.WORD oam_enemies_frameset_35
	.WORD oam_enemies_frameset_36
	.WORD oam_enemies_frameset_37
	.WORD oam_enemies_frameset_38
	.WORD oam_enemies_frameset_39
	.WORD oam_enemies_frameset_3a
	.WORD oam_enemies_frameset_3b
	.WORD oam_enemies_frameset_3c
	.WORD oam_enemies_frameset_3d
	.WORD oam_enemies_frameset_3e
	.WORD oam_enemies_frameset_3f
	.WORD oam_enemies_frameset_40
	.WORD oam_enemies_frameset_41
	.WORD oam_enemies_frameset_42
	.WORD oam_enemies_frameset_43
	.WORD oam_enemies_frameset_44
	.WORD oam_enemies_frameset_45
	.WORD oam_enemies_frameset_46
	.WORD oam_enemies_frameset_47
	.WORD oam_enemies_frameset_48
	.WORD oam_enemies_frameset_49
	.WORD oam_enemies_frameset_4a
