oam_frameset_pointers:
	.WORD oam_frameset_00
	.WORD oam_frameset_01
	.WORD oam_frameset_02
	.WORD oam_frameset_03
	.WORD oam_frameset_04
	.WORD oam_frameset_05
	.WORD oam_frameset_06
	.WORD oam_frameset_07
	.WORD oam_frameset_08
	.WORD oam_frameset_09
	.WORD oam_frameset_0a
	.WORD oam_frameset_0b
	.WORD oam_frameset_0c
	.WORD oam_frameset_0d
	.WORD oam_frameset_0e
	.WORD oam_frameset_0f
	.WORD oam_frameset_10
	.WORD oam_frameset_11
	.WORD oam_frameset_12
	.WORD oam_frameset_13
	.WORD oam_frameset_14
	.WORD oam_frameset_15
	.WORD oam_frameset_16
	.WORD oam_frameset_17
	.WORD oam_frameset_18
	.WORD oam_frameset_19
	.WORD oam_frameset_1a
	.WORD oam_frameset_1b
	.WORD oam_frameset_1c
	.WORD oam_frameset_1d
	.WORD oam_frameset_1e
	.WORD oam_frameset_1f
	.WORD oam_frameset_20
	.WORD oam_frameset_21
	.WORD oam_frameset_22
	.WORD oam_frameset_23
	.WORD oam_frameset_24
	.WORD oam_frameset_25
	.WORD oam_frameset_26
	.WORD oam_frameset_27
	.WORD oam_frameset_28
	.WORD oam_frameset_29
	.WORD oam_frameset_2a
	.WORD oam_frameset_2b
	.WORD oam_frameset_2c
	.WORD oam_frameset_2d
	.WORD oam_frameset_2e
	.WORD oam_frameset_2f
	.WORD oam_frameset_30
	.WORD oam_frameset_31
	.WORD oam_frameset_32
	.WORD oam_frameset_33
	.WORD oam_frameset_34
	.WORD oam_frameset_35
	.WORD oam_frameset_36
	.WORD oam_frameset_37
	.WORD oam_frameset_38
	.WORD oam_frameset_39
	.WORD oam_frameset_3a
	.WORD oam_frameset_3b
	.WORD oam_frameset_3c
	.WORD oam_frameset_3d
	.WORD oam_frameset_3e
	.WORD oam_frameset_3f
	.WORD oam_frameset_40
	.WORD oam_frameset_41
	.WORD oam_frameset_42
	.WORD oam_frameset_43
	.WORD oam_frameset_44
	.WORD oam_frameset_45
	.WORD oam_frameset_46
	.WORD oam_frameset_47
	.WORD oam_frameset_48
	.WORD oam_frameset_49
	.WORD oam_frameset_4a
	.WORD oam_frameset_4b
	.WORD oam_frameset_4c
	.WORD oam_frameset_4d
	.WORD oam_frameset_4e
	.WORD oam_frameset_4f
	.WORD oam_frameset_50
	.WORD oam_frameset_51
	.WORD oam_frameset_52
	.WORD oam_frameset_53
	.WORD oam_frameset_54
	.WORD oam_frameset_55
	.WORD oam_frameset_56
	.WORD oam_frameset_57
	.WORD oam_frameset_58
	.WORD oam_frameset_59
	.WORD oam_frameset_5a
	.WORD oam_frameset_5b
	.WORD oam_frameset_5c
	.WORD oam_frameset_5d
	.WORD oam_frameset_5e
	.WORD oam_frameset_5f
	.WORD oam_frameset_60
	.WORD oam_frameset_61
	.WORD oam_frameset_62
	.WORD oam_frameset_63
	.WORD oam_frameset_64
	.WORD oam_frameset_65
	.WORD oam_frameset_66
	.WORD oam_frameset_67
	.WORD oam_frameset_68
	.WORD oam_frameset_69
	.WORD oam_frameset_6a
	.WORD oam_frameset_6b
	.WORD oam_frameset_6c
	.WORD oam_frameset_6d
	.WORD oam_frameset_6e
	.WORD oam_frameset_6f
	.WORD oam_frameset_70
	.WORD oam_frameset_71
	.WORD oam_frameset_72
	.WORD oam_frameset_73
	.WORD oam_frameset_74
	.WORD oam_frameset_75
	.WORD oam_frameset_76
	.WORD oam_frameset_77
	.WORD oam_frameset_78
	.WORD oam_frameset_79
	.WORD oam_frameset_7a
	.WORD oam_frameset_7b
	.WORD oam_frameset_7c
	.WORD oam_frameset_7d
	.WORD oam_frameset_7e
	.WORD oam_frameset_7f
	.WORD oam_frameset_80
	.WORD oam_frameset_81
	.WORD oam_frameset_82
	.WORD oam_frameset_83
	.WORD oam_frameset_84
	.WORD oam_frameset_85
	.WORD oam_frameset_86
	.WORD oam_frameset_87
	.WORD oam_frameset_88
	.WORD oam_frameset_89
	.WORD oam_frameset_8a
	.WORD oam_frameset_8b
	.WORD oam_frameset_8c
	.WORD oam_frameset_8d
	.WORD oam_frameset_8e
	.WORD oam_frameset_8f
	.WORD oam_frameset_90
	.WORD oam_frameset_91
