;oamcoord index pointers
	.WORD oamcoord_index_00
	.WORD oamcoord_index_01
	.WORD oamcoord_index_02
	.WORD oamcoord_index_03
	.WORD oamcoord_index_04
	.WORD oamcoord_index_05
	.WORD oamcoord_index_06
	.WORD oamcoord_index_07
	.WORD oamcoord_index_08
	.WORD oamcoord_index_09
	.WORD oamcoord_index_0a
	.WORD oamcoord_index_0b
	.WORD oamcoord_index_0c
	.WORD oamcoord_index_0d
	.WORD oamcoord_index_0e
	.WORD oamcoord_index_0f
	.WORD oamcoord_index_10
	.WORD oamcoord_index_11
	.WORD oamcoord_index_12
	.WORD oamcoord_index_13
	.WORD oamcoord_index_14
	.WORD oamcoord_index_15
	.WORD oamcoord_index_16
	.WORD oamcoord_index_17
	.WORD oamcoord_index_18
	.WORD oamcoord_index_19
	.WORD oamcoord_index_1a
	.WORD oamcoord_index_1b
	.WORD oamcoord_index_1c
	.WORD oamcoord_index_1d
	.WORD oamcoord_index_1e
	.WORD oamcoord_index_1f
	.WORD oamcoord_index_20
	.WORD oamcoord_index_21
	.WORD oamcoord_index_22
	.WORD oamcoord_index_23
	.WORD oamcoord_index_24
	.WORD oamcoord_index_25
	.WORD oamcoord_index_26
	.WORD oamcoord_index_27
	.WORD oamcoord_index_28
	.WORD oamcoord_index_29
	.WORD oamcoord_index_2a
	.WORD oamcoord_index_2b
	.WORD oamcoord_index_2c
	.WORD oamcoord_index_2d
	.WORD oamcoord_index_2e
	.WORD oamcoord_index_2f
	.WORD oamcoord_index_30
	.WORD oamcoord_index_31
	.WORD oamcoord_index_32
	.WORD oamcoord_index_33
	.WORD oamcoord_index_34
	.WORD oamcoord_index_35
	.WORD oamcoord_index_36
	.WORD oamcoord_index_37
	.WORD oamcoord_index_38
	.WORD oamcoord_index_39
	.WORD oamcoord_index_3a
	.WORD oamcoord_index_3b
	.WORD oamcoord_index_3c
	.WORD oamcoord_index_3d
	.WORD oamcoord_index_3e
	.WORD oamcoord_index_3f
	.WORD oamcoord_index_40
	.WORD oamcoord_index_41
	.WORD oamcoord_index_42
	.WORD oamcoord_index_43
	.WORD oamcoord_index_44

;end
	.BYTE $00, $00, $00, $00, $00, $00
